import { useEffect } from 'react';
import { Sparkles, ChevronDown, Copy, AlertCircle, RotateCcw, Zap, Users, DollarSign, Share2, Loader2, FileText, CheckCircle2 } from 'lucide-react';
import { useApp } from '../contexts/AppContext';
import { AdCopyRightPanel } from './ad-copy/components/AdCopyRightPanel';
import { useAdCopy } from './ad-copy/hooks/useAdCopy';

const ANALYSIS_MODELS = [
  { id: 'google/gemini-2.5-flash', label: 'Gemini 2.5 Flash', description: 'سريع وذكي — مثالي لمعظم المنتجات.' },
  { id: 'google/gemini-2.5-pro', label: 'Gemini 2.5 Pro', description: 'أعمق تحليل — للمنتجات المعقدة.' },
  { id: 'anthropic/claude-3-5-sonnet', label: 'Claude 3.5 Sonnet', description: 'إبداع لغوي عالي المستوى.' },
  { id: 'openai/gpt-4o', label: 'GPT-4o', description: 'قراءة دقيقة للصور.' },
];

export function AdCopyScreen() {
  const { setRightPanelContent } = useApp();
  const {
    isGenerating,
    analysisModel,
    setAnalysisModel,
    productImageUrl,
    aiAnalysis,
    generatedVariants,
    generationError,
    showResults,
    modelDropdownOpen,
    setModelDropdownOpen,
    copiedIndex,
    handleImageUpload,
    handleStartOver,
    copyToClipboard
  } = useAdCopy();

  const selectedModelLabel = ANALYSIS_MODELS.find(m => m.id === analysisModel)?.label ?? analysisModel;

  // Render the Right Panel API Costs
  useEffect(() => {
    setRightPanelContent(<AdCopyRightPanel currentModelLabel={selectedModelLabel} />);
    return () => setRightPanelContent(null);
  }, [setRightPanelContent, selectedModelLabel]);


  // === RENDER: GENERATING LOADING VIEW ===
  if (isGenerating) {
    return (
      <div style={{ height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--font-body)' }}>
        <Loader2 className="animate-spin" size={48} color="var(--ma-accent)" style={{ marginBottom: 24 }} />
        <h2 style={{ fontSize: 24, fontWeight: 700, color: '#FFF' }}>Building Your Strategy...</h2>
        <p style={{ color: 'rgba(255,255,255,0.5)', marginTop: 8, maxWidth: 400, textAlign: 'center', lineHeight: 1.6 }}>
          Our AI is analyzing the product visual, determining the optimal audience and pricing tier, and writing high-converting ad copy.
        </p>
      </div>
    );
  }

  // === RENDER: ERROR VIEW ===
  if (generationError) {
    return (
      <div style={{ height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', fontFamily: 'var(--font-body)', padding: 40 }}>
        <AlertCircle size={48} color="#EF4444" style={{ marginBottom: 20 }} />
        <h2 style={{ fontSize: 20, fontWeight: 600, color: '#FFF', marginBottom: 12 }}>Generation Failed</h2>
        <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.5)', textAlign: 'center', maxWidth: 480, lineHeight: 1.6, marginBottom: 24 }}>
          {generationError}
        </p>
        <button onClick={handleStartOver} style={{ padding: '12px 28px', background: 'var(--ma-border)', borderRadius: 8, color: '#FFF', cursor: 'pointer' }}>
          Back to Start
        </button>
      </div>
    );
  }

  // === RENDER: RESULTS VIEW ===
  if (showResults && aiAnalysis) {
    return (
      <div style={{ padding: '32px 36px', height: '100%', overflowY: 'auto' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 32 }}>
          <div>
            <h1 style={{ fontSize: 28, fontWeight: 800, color: '#FFF', letterSpacing: -0.5, marginBottom: 8 }}>The Strategic Marketing Plan</h1>
            <p style={{ color: 'rgba(255,255,255,0.6)', display: 'flex', alignItems: 'center', gap: 6, fontSize: 13 }}>
              <Zap size={14} color="var(--ma-accent)" /> Strategy generated by {selectedModelLabel}
            </p>
          </div>
          <button onClick={handleStartOver} style={{ padding: '10px 18px', background: 'var(--ma-elevated)', border: '1px solid var(--ma-border)', borderRadius: 8, color: '#FFF', fontSize: 13, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6 }}>
            <RotateCcw size={14} /> New Campaign
          </button>
        </div>

        {/* AI Identified Strategy Summary */}
        <div style={{ background: 'var(--ma-card)', border: '1px solid var(--ma-border)', borderRadius: 16, padding: '24px 32px', marginBottom: 32, display: 'flex', gap: 40, alignItems: 'center' }}>
          {productImageUrl && (
            <div style={{ flexShrink: 0 }}>
              <img src={productImageUrl} alt="Product" style={{ width: 140, height: 140, objectFit: 'contain', borderRadius: 12, background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.1)' }} />
            </div>
          )}
          
          <div style={{ flex: 1, display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 24 }}>
            <div>
              <span style={{ fontSize: 10, fontWeight: 700, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: 1, display: 'block', marginBottom: 6 }}>Identified Product</span>
              <div style={{ fontSize: 18, fontWeight: 600, color: '#FFF' }}>{aiAnalysis.product}</div>
              <div style={{ fontSize: 14, color: 'rgba(255,255,255,0.5)', marginTop: 4 }}>{aiAnalysis.category} • {aiAnalysis.material}</div>
            </div>
            <div>
              <span style={{ fontSize: 10, fontWeight: 700, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: 1, display: 'block', marginBottom: 6 }}><Users size={12} style={{ display: 'inline', marginRight: 4, verticalAlign: '-2px' }} /> Target Audience</span>
              <div style={{ fontSize: 14, color: '#FFF', lineHeight: 1.5 }}>{aiAnalysis.targetAudience}</div>
            </div>
            <div>
              <span style={{ fontSize: 10, fontWeight: 700, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: 1, display: 'block', marginBottom: 6 }}><DollarSign size={12} style={{ display: 'inline', marginRight: 4, verticalAlign: '-2px' }} /> Suggested Pricing Tier</span>
              <div style={{ fontSize: 14, color: 'var(--ma-green)', fontWeight: 600 }}>{aiAnalysis.priceTier?.toUpperCase()}</div>
            </div>
            <div>
              <span style={{ fontSize: 10, fontWeight: 700, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', letterSpacing: 1, display: 'block', marginBottom: 6 }}><Share2 size={12} style={{ display: 'inline', marginRight: 4, verticalAlign: '-2px' }} /> Best Platforms</span>
              <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                {aiAnalysis.recommendedPlatforms?.map((p, i) => (
                   <span key={i} style={{ padding: '4px 10px', background: 'rgba(108,99,255,0.15)', color: 'var(--ma-accent)', borderRadius: 100, fontSize: 12, fontWeight: 500 }}>{p}</span>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Generated Copy Variants */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
          <div style={{ width: 24, height: 24, borderRadius: '50%', background: 'var(--ma-accent)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <FileText size={12} color="#FFF" />
          </div>
          <h2 style={{ fontSize: 18, fontWeight: 600, color: '#FFF' }}>Direct Response Copy Variants</h2>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: 24, paddingBottom: 40 }}>
          {generatedVariants.map((variant, idx) => (
            <div key={idx} style={{ background: 'var(--ma-card)', border: '1px solid var(--ma-border)', borderRadius: 16, padding: 24, position: 'relative' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
                <span style={{ fontSize: 11, fontWeight: 700, color: 'var(--ma-accent)', textTransform: 'uppercase', letterSpacing: 1 }}>{variant.variantType} Angle</span>
                <button 
                  onClick={() => copyToClipboard(variant.bodyCopy, idx)} 
                  style={{ background: 'transparent', border: 'none', color: copiedIndex === idx ? 'var(--ma-green)' : 'rgba(255,255,255,0.4)', cursor: 'pointer', transition: 'color 0.2s', display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, fontWeight: 600 }} 
                  title="Copy full text"
                >
                  {copiedIndex === idx ? <><CheckCircle2 size={16} /> Copied!</> : <><Copy size={16} /> Copy Copy</>}
                </button>
              </div>
              <div style={{ direction: 'rtl', textAlign: 'right' }}>
                <h3 style={{ fontSize: 18, fontWeight: 600, color: '#FFF', marginBottom: 12, lineHeight: 1.4 }}>{variant.headline1}</h3>
                <div style={{ fontSize: 13, color: 'var(--ma-yellow)', fontWeight: 600, marginBottom: 16, display: 'inline-block', background: 'rgba(250, 204, 21, 0.1)', padding: '4px 8px', borderRadius: 6 }}>
                  Hook: {variant.hook}
                </div>
                <p style={{ fontSize: 14, color: 'rgba(255,255,255,0.8)', lineHeight: 1.6, marginBottom: 20, whiteSpace: 'pre-wrap' }}>{variant.bodyCopy}</p>
                <div style={{ color: 'var(--ma-accent)', fontWeight: 700, fontSize: 14 }}>{variant.cta}</div>
              </div>
              
              <div style={{ marginTop: 24, paddingTop: 16, borderTop: '1px solid rgba(255,255,255,0.05)', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, direction: 'rtl', textAlign: 'right' }}>
                <div>
                  <span style={{ fontSize: 10, color: 'rgba(255,255,255,0.3)', textTransform: 'uppercase', letterSpacing: 0.5, fontWeight: 600 }}>المحفز النفسي</span>
                  <p style={{ fontSize: 12, color: 'rgba(255,255,255,0.6)', marginTop: 6, lineHeight: 1.4 }}>{variant.triggersUsed}</p>
                </div>
                <div>
                  <span style={{ fontSize: 10, color: 'rgba(255,255,255,0.3)', textTransform: 'uppercase', letterSpacing: 0.5, fontWeight: 600 }}>فكرة خطاف الفيديو</span>
                  <p style={{ fontSize: 12, color: 'rgba(255,255,255,0.6)', marginTop: 6, lineHeight: 1.4 }}>{variant.videoScripts}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  // === RENDER: INITIAL UPLOAD VIEW ===
  return (
    <div style={{ 
      height: '100%', 
      display: 'flex', 
      alignItems: 'center', 
      justifyContent: 'center', 
      fontFamily: 'var(--font-body)',
      background: 'radial-gradient(circle at top right, rgba(108, 99, 255, 0.05), transparent)'
    }}>
      <div style={{ width: '100%', maxWidth: 500, padding: 40, textAlign: 'center' }}>
        <div style={{ 
          width: 80, height: 80, background: 'rgba(108, 99, 255, 0.1)', 
          borderRadius: 24, display: 'flex', alignItems: 'center', 
          justifyContent: 'center', margin: '0 auto 24px',
          border: '1px solid rgba(108, 99, 255, 0.2)'
        }}>
          <Sparkles size={40} color="var(--ma-accent)" />
        </div>
        
        <h1 style={{ fontSize: 32, fontWeight: 800, color: '#FFF', marginBottom: 12, letterSpacing: -1 }}>AI Creative Strategist</h1>
        <p style={{ fontSize: 16, color: 'rgba(255,255,255,0.5)', lineHeight: 1.6, marginBottom: 32 }}>
          Drop an image of your product. The AI will determine the optimal audience, price framing, and generate ready-to-run Arabic direct response ads.
        </p>

        <div style={{ marginBottom: 24, textAlign: 'left' }}>
          <label style={{ fontSize: 11, fontWeight: 600, color: 'rgba(255,255,255,0.4)', textTransform: 'uppercase', marginBottom: 8, display: 'block' }}>Vision & Strategy Model</label>
          <div style={{ position: 'relative' }}>
            <div 
              style={{
                width: '100%', padding: '14px 16px', background: 'var(--ma-elevated)',
                border: '1px solid var(--ma-border)', borderRadius: 12, color: '#FFF',
                fontSize: 14, cursor: 'pointer', display: 'flex', justifyContent: 'space-between', alignItems: 'center'
              }}
              onClick={() => setModelDropdownOpen(!modelDropdownOpen)}
            >
              <span>{selectedModelLabel}</span>
              <ChevronDown size={16} color="rgba(255,255,255,0.5)" />
            </div>
            
            {modelDropdownOpen && (
              <div style={{
                position: 'absolute', top: '100%', left: 0, right: 0, marginTop: 8,
                background: '#1A1A1A', border: '1px solid var(--ma-border)', borderRadius: 12,
                overflow: 'hidden', zIndex: 10, boxShadow: '0 10px 40px rgba(0,0,0,0.5)'
              }}>
                {ANALYSIS_MODELS.map(m => (
                  <div 
                    key={m.id}
                    onClick={() => { setAnalysisModel(m.id); setModelDropdownOpen(false); }}
                    style={{
                      padding: '12px 16px', borderBottom: '1px solid rgba(255,255,255,0.05)',
                      cursor: 'pointer', backgroundColor: m.id === analysisModel ? 'rgba(108,99,255,0.1)' : 'transparent'
                    }}
                  >
                    <div style={{ fontSize: 14, fontWeight: 600, color: '#FFF', marginBottom: 2 }}>{m.label}</div>
                    <div style={{ fontSize: 12, color: 'rgba(255,255,255,0.4)' }}>{m.description}</div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        <input type="file" accept="image/*" onChange={handleImageUpload} style={{ display: 'none' }} id="initial-upload" />
        <label 
          htmlFor="initial-upload" 
          style={{ 
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 12,
            padding: '18px 32px', background: 'var(--ma-accent)',
            borderRadius: 14, color: '#FFF', fontSize: 16, fontWeight: 700, 
            cursor: 'pointer',
            boxShadow: '0 4px 20px rgba(108, 99, 255, 0.3)',
            transition: 'all 0.2s'
          }}
        >
          <Zap size={20} /> Generate Launch Plan
        </label>
      </div>

      <style>{`
        .animate-spin { animation: spin 1s linear infinite; }
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
        ::-webkit-scrollbar { width: 8px; }
        ::-webkit-scrollbar-track { background: rgba(0,0,0,0.1); }
        ::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.1); border-radius: 4px; }
      `}</style>
    </div>
  );
}
