import {
  RotateCcw,
  Zap,
  Users,
  DollarSign,
  Share2,
  FileText,
  CheckCircle2,
  Copy
} from 'lucide-react'
import { ProductAnalysis } from '../../../services/anthropic.service'
import { CopyVariant } from '../../../services/fal.service'

interface AdCopyResultsPanelProps {
  showResults: boolean
  aiAnalysis: ProductAnalysis | null
  productImageUrl: string | null
  generatedVariants: CopyVariant[]
  copiedIndex: number | null
  copyToClipboard: (text: string, idx: number) => void
  handleStartOver: () => void
  selectedModelLabel: string
  adLanguage: string
}

export function AdCopyResultsPanel(props: AdCopyResultsPanelProps) {
  const {
    showResults,
    aiAnalysis,
    productImageUrl,
    generatedVariants,
    copiedIndex,
    copyToClipboard,
    handleStartOver,
    selectedModelLabel,
    adLanguage
  } = props

  if (!showResults || !aiAnalysis) return null

  const isRtl = adLanguage === 'arabic'

  const renderString = (val: any): string => {
    if (typeof val === 'string') return val
    if (typeof val === 'number' || typeof val === 'boolean') return String(val)
    if (Array.isArray(val)) return val.join(', ')
    if (val && typeof val === 'object') return Object.keys(val).join(', ')
    return ''
  }

  return (
    <div style={{ padding: '32px 36px', height: '100%', overflowY: 'auto' }}>
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'flex-start',
          marginBottom: 32
        }}
      >
        <div>
          <h1
            style={{
              fontSize: 28,
              fontWeight: 800,
              color: '#FFF',
              letterSpacing: -0.5,
              marginBottom: 8
            }}
          >
            The Strategic Marketing Plan
          </h1>
          <p
            style={{
              color: 'rgba(255,255,255,0.6)',
              display: 'flex',
              alignItems: 'center',
              gap: 6,
              fontSize: 13
            }}
          >
            <Zap size={14} color="var(--ma-accent)" /> Strategy generated by {selectedModelLabel}
          </p>
        </div>
        <button
          onClick={handleStartOver}
          style={{
            padding: '10px 18px',
            background: 'var(--ma-elevated)',
            border: '1px solid var(--ma-border)',
            borderRadius: 8,
            color: '#FFF',
            fontSize: 13,
            cursor: 'pointer',
            display: 'flex',
            alignItems: 'center',
            gap: 6
          }}
        >
          <RotateCcw size={14} /> New Campaign
        </button>
      </div>

      {/* AI Identified Strategy Summary */}
      <div
        style={{
          background: 'var(--ma-card)',
          border: '1px solid var(--ma-border)',
          borderRadius: 16,
          padding: '24px 32px',
          marginBottom: 32,
          display: 'flex',
          gap: 40,
          alignItems: 'center'
        }}
      >
        {productImageUrl && (
          <div style={{ flexShrink: 0 }}>
            <img
              src={productImageUrl}
              alt="Product"
              style={{
                width: 140,
                height: 140,
                objectFit: 'contain',
                borderRadius: 12,
                background: 'rgba(0,0,0,0.2)',
                border: '1px solid rgba(255,255,255,0.1)'
              }}
            />
          </div>
        )}

        <div style={{ flex: 1, display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 24 }}>
          <div>
            <span
              style={{
                fontSize: 10,
                fontWeight: 700,
                color: 'rgba(255,255,255,0.4)',
                textTransform: 'uppercase',
                letterSpacing: 1,
                display: 'block',
                marginBottom: 6
              }}
            >
              Identified Product
            </span>
            <div style={{ fontSize: 18, fontWeight: 600, color: '#FFF' }}>
              {renderString(aiAnalysis.product)}
            </div>
            <div style={{ fontSize: 14, color: 'rgba(255,255,255,0.5)', marginTop: 4 }}>
              {renderString(aiAnalysis.category)} • {renderString(aiAnalysis.material)}
            </div>
          </div>
          <div>
            <span
              style={{
                fontSize: 10,
                fontWeight: 700,
                color: 'rgba(255,255,255,0.4)',
                textTransform: 'uppercase',
                letterSpacing: 1,
                display: 'block',
                marginBottom: 6
              }}
            >
              <Users
                size={12}
                style={{ display: 'inline', marginRight: 4, verticalAlign: '-2px' }}
              />{' '}
              Target Audience
            </span>
            <div style={{ fontSize: 14, color: '#FFF', lineHeight: 1.5 }}>
              {renderString(aiAnalysis.targetAudience)}
            </div>
          </div>
          <div>
            <span
              style={{
                fontSize: 10,
                fontWeight: 700,
                color: 'rgba(255,255,255,0.4)',
                textTransform: 'uppercase',
                letterSpacing: 1,
                display: 'block',
                marginBottom: 6
              }}
            >
              <DollarSign
                size={12}
                style={{ display: 'inline', marginRight: 4, verticalAlign: '-2px' }}
              />{' '}
              Suggested Pricing Tier
            </span>
            <div style={{ fontSize: 14, color: 'var(--ma-green)', fontWeight: 600 }}>
              {renderString(aiAnalysis.priceTier).toUpperCase()}
            </div>
          </div>
          <div>
            <span
              style={{
                fontSize: 10,
                fontWeight: 700,
                color: 'rgba(255,255,255,0.4)',
                textTransform: 'uppercase',
                letterSpacing: 1,
                display: 'block',
                marginBottom: 6
              }}
            >
              <Share2
                size={12}
                style={{ display: 'inline', marginRight: 4, verticalAlign: '-2px' }}
              />{' '}
              Best Platforms
            </span>
            <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
              {Array.isArray(aiAnalysis.recommendedPlatforms) ? (
                aiAnalysis.recommendedPlatforms.map((p: any, i: number) => {
                  const label = typeof p === 'object' ? Object.keys(p).join(', ') : String(p)
                  return (
                    <span
                      key={i}
                      style={{
                        padding: '4px 10px',
                        background: 'rgba(108,99,255,0.15)',
                        color: 'var(--ma-accent)',
                        borderRadius: 100,
                        fontSize: 12,
                        fontWeight: 500
                      }}
                    >
                      {label}
                    </span>
                  )
                })
              ) : typeof aiAnalysis.recommendedPlatforms === 'string' ? (
                <span
                  style={{
                    padding: '4px 10px',
                    background: 'rgba(108,99,255,0.15)',
                    color: 'var(--ma-accent)',
                    borderRadius: 100,
                    fontSize: 12,
                    fontWeight: 500
                  }}
                >
                  {aiAnalysis.recommendedPlatforms}
                </span>
              ) : typeof aiAnalysis.recommendedPlatforms === 'object' &&
                aiAnalysis.recommendedPlatforms !== null ? (
                Object.keys(aiAnalysis.recommendedPlatforms).map((k, i) => (
                  <span
                    key={i}
                    style={{
                      padding: '4px 10px',
                      background: 'rgba(108,99,255,0.15)',
                      color: 'var(--ma-accent)',
                      borderRadius: 100,
                      fontSize: 12,
                      fontWeight: 500
                    }}
                  >
                    {k}
                  </span>
                ))
              ) : null}
            </div>
          </div>
        </div>
      </div>

      {/* Generated Copy Variants */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
        <div
          style={{
            width: 24,
            height: 24,
            borderRadius: '50%',
            background: 'var(--ma-accent)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}
        >
          <FileText size={12} color="#FFF" />
        </div>
        <h2 style={{ fontSize: 18, fontWeight: 600, color: '#FFF' }}>
          Direct Response Copy Variants
        </h2>
      </div>

      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))',
          gap: 24,
          paddingBottom: 40
        }}
      >
        {generatedVariants.map((variant, idx) => (
          <div
            key={idx}
            style={{
              background: 'var(--ma-card)',
              border: '1px solid var(--ma-border)',
              borderRadius: 16,
              padding: 24,
              position: 'relative'
            }}
          >
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
              <span
                style={{
                  fontSize: 11,
                  fontWeight: 700,
                  color: 'var(--ma-accent)',
                  textTransform: 'uppercase',
                  letterSpacing: 1
                }}
              >
                {renderString(variant.variantType)} Angle
              </span>
              <button
                onClick={() =>
                  copyToClipboard(
                    typeof variant.bodyCopy === 'string'
                      ? variant.bodyCopy
                      : JSON.stringify(variant.bodyCopy),
                    idx
                  )
                }
                style={{
                  background: 'transparent',
                  border: 'none',
                  color: copiedIndex === idx ? 'var(--ma-green)' : 'rgba(255,255,255,0.4)',
                  cursor: 'pointer',
                  transition: 'color 0.2s',
                  display: 'flex',
                  alignItems: 'center',
                  gap: 6,
                  fontSize: 12,
                  fontWeight: 600
                }}
                title="Copy full text"
              >
                {copiedIndex === idx ? (
                  <>
                    <CheckCircle2 size={16} /> Copied!
                  </>
                ) : (
                  <>
                    <Copy size={16} /> Copy Copy
                  </>
                )}
              </button>
            </div>
            <div style={{ direction: isRtl ? 'rtl' : 'ltr', textAlign: isRtl ? 'right' : 'left' }}>
              <h3
                style={{
                  fontSize: 18,
                  fontWeight: 600,
                  color: '#FFF',
                  marginBottom: 12,
                  lineHeight: 1.4
                }}
              >
                {renderString(variant.headline1)}
              </h3>
              <div
                style={{
                  fontSize: 13,
                  color: 'var(--ma-yellow)',
                  fontWeight: 600,
                  marginBottom: 16,
                  display: 'inline-block',
                  background: 'rgba(250, 204, 21, 0.1)',
                  padding: '4px 8px',
                  borderRadius: 6
                }}
              >
                Hook: {renderString(variant.hook)}
              </div>
              <p
                style={{
                  fontSize: 14,
                  color: 'rgba(255,255,255,0.8)',
                  lineHeight: 1.6,
                  marginBottom: 20,
                  whiteSpace: 'pre-wrap'
                }}
              >
                {renderString(variant.bodyCopy)}
              </p>
              <div style={{ color: 'var(--ma-accent)', fontWeight: 700, fontSize: 14 }}>
                {renderString(variant.cta)}
              </div>
            </div>

            <div
              style={{
                marginTop: 24,
                paddingTop: 16,
                borderTop: '1px solid rgba(255,255,255,0.05)',
                display: 'grid',
                gridTemplateColumns: '1fr 1fr',
                gap: 16,
                direction: isRtl ? 'rtl' : 'ltr',
                textAlign: isRtl ? 'right' : 'left'
              }}
            >
              <div>
                <span
                  style={{
                    fontSize: 10,
                    color: 'rgba(255,255,255,0.3)',
                    textTransform: 'uppercase',
                    letterSpacing: 0.5,
                    fontWeight: 600
                  }}
                >
                  {isRtl ? 'المحفز النفسي' : 'Psychological Trigger'}
                </span>
                <p
                  style={{
                    fontSize: 12,
                    color: 'rgba(255,255,255,0.6)',
                    marginTop: 6,
                    lineHeight: 1.4
                  }}
                >
                  {renderString(variant.triggersUsed)}
                </p>
              </div>
              <div>
                <span
                  style={{
                    fontSize: 10,
                    color: 'rgba(255,255,255,0.3)',
                    textTransform: 'uppercase',
                    letterSpacing: 0.5,
                    fontWeight: 600
                  }}
                >
                  {isRtl ? 'فكرة خطاف الفيديو' : 'Video Hook Script'}
                </span>
                <p
                  style={{
                    fontSize: 12,
                    color: 'rgba(255,255,255,0.6)',
                    marginTop: 6,
                    lineHeight: 1.4
                  }}
                >
                  {renderString(variant.videoScripts)}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
